basic:
    intrinsic_file: asset/NC_12002_10/cam_matrix.yaml
    extrinsic_file: asset/NC_12002_10/pmtd_image.bin
    image_topic: /pmtd/csi_camera/image_bgr
    lidar_topic: /livox/lidar
    fusion_pub_topic: /usion_cloud
    distance_valid: 200
